apiVersion: v1
kind: Service
metadata:
  name: {{ include "ik-app.name" . }}
  labels:
    {{- include "ik-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ik-app.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if gt (int .Values.replicas) 1 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ik-app.name" . }}
  labels:
    {{- include "ik-app.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "ik-app.selector" . | nindent 6 }}
{{- end }}
