name: PR Checker
on:
  workflow_dispatch:

  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend_any_changed }}
      frontend: ${{ steps.filter.outputs.frontend_any_changed }}
      charts: ${{ steps.filter.outputs.charts_any_changed }}
      docs: ${{ steps.filter.outputs.docs_any_changed }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: tj-actions/changed-files@v47
        id: filter
        with:
          files_yaml: |
            backend:
              - server/**
              - VERSION
            frontend:
              - ui/**
              - VERSION
            docs:
              - docs/**
              - package.json
              - package-lock.json
              - blume.config.ts

  lint-python:
    name: Lint Python code
    if: ${{ needs.changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs:
      - changes
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: server

      - name: Run python-linter
        run: |
          ./scripts/check_python_types.sh
          echo "check formatting"
          ./scripts/check_ruff_formatting.sh

      - name: Run python-tests
        run: |
          ./scripts/run_python_tests.sh

  lint-ui:
    name: Lint UI code
    if: ${{ needs.changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs:
      - changes
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Run ESLint
        run: ./scripts/check_typescript.sh

  lint-docs:
    name: Validate and build docs
    if: ${{ needs.changes.outputs.docs == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs:
      - changes
    steps:
      - uses: actions/checkout@v7.0.0

      - name: use node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate docs
        run: npm run validate

      - name: Build docs
        run: npm run build
